/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src/assets/Zombie2.glb -o src/components/Zombie2.jsx -r public 
*/

import React, { useEffect, useMemo, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useGraph } from "@react-three/fiber";
import { SkeletonUtils } from "three-stdlib";

export function Zombie2(props) {
  const group = useRef();
  const { materials, animations, scene } = useGLTF(
    "/../src/assets/Zombie2.glb"
  );

  useEffect(() => {
    actions[props.animation].reset().fadeIn(0.5).play();
    return () => actions[props.animation]?.fadeOut(0.5);
  }, [props.animation]);

  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { actions } = useAnimations(animations, group);
  const { nodes } = useGraph(clone);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Root_Scene">
        <group name="RootNode">
          <group
            name="CharacterArmature"
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <primitive object={nodes.Root} />
          </group>
          <skinnedMesh
            name="Face"
            geometry={nodes.Face.geometry}
            material={materials.Atlas}
            skeleton={nodes.Face.skeleton}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <skinnedMesh
            name="Tongue"
            geometry={nodes.Tongue.geometry}
            material={materials.Atlas}
            skeleton={nodes.Tongue.skeleton}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <skinnedMesh
            name="Zombie_Chubby"
            geometry={nodes.Zombie_Chubby.geometry}
            material={materials.Atlas}
            skeleton={nodes.Zombie_Chubby.skeleton}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/../src/assets/Zombie2.glb");
